version: 2.1
jobs:
  lint:
    docker:
      - image: node:10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: yarn lint

  deploy-staging:
    docker:
      - image: node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - run:
          name: Building staging site
          command: yarn stage
      - run:
          name: Deploy to staging
          command: |
            cp ./dist/index.html ./dist/200.html
            ./node_modules/surge/lib/cli.js --project ./dist --domain gep-explorer.surge.sh

  build-production:
    docker:
      - image: node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
              - dist

  deploy-production:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Sync files at S3
          command: aws s3 sync --delete /tmp/workspace/dist s3://${PRODUCTION_S3_BUCKET}/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - lint
      - deploy-staging:
          requires:
            - lint
          filters:
            branches:
              only: develop
      - build-production:
          requires:
            - lint
          filters:
            branches:
              only: master
      - deploy-production:
          requires:
            - build-production
          filters:
            branches:
              only: master
